"""Finite automorphism-group image explorer."""

from __future__ import annotations

import streamlit as st

from rubin_subshifts.app.components.explanations import finite_disclaimer
from rubin_subshifts.cellular_automata.automata import CellularAutomaton
from rubin_subshifts.groups.finite_actions import induced_permutation
from rubin_subshifts.groups.generated_groups import generate_group
from rubin_subshifts.groups.orbits import orbits
from rubin_subshifts.symbolic.alphabet import Alphabet
from rubin_subshifts.symbolic.configurations import enumerate_periodic_configurations
from rubin_subshifts.visualization.groups import element_order_figure, orbit_size_figure


def render() -> None:
    """Render a finite permutation image generated by the shift."""
    st.title("Automorphism Group Explorer")
    finite_disclaimer()
    period = st.sidebar.slider("Periodic domain", 1, 10, 5)
    cap = st.sidebar.slider("Group-closure cap", 1, 1_000, 100)
    direction = st.sidebar.selectbox("Generator", ("Left shift", "Right shift"))
    alphabet = Alphabet((0, 1))
    automaton = (
        CellularAutomaton.left_shift(alphabet)
        if direction == "Left shift"
        else CellularAutomaton.right_shift(alphabet)
    )
    if st.button("Generate finite permutation image"):
        domain = tuple(enumerate_periodic_configurations(alphabet, period))
        generator = induced_permutation(automaton, domain)
        group = generate_group((generator,), max_elements=cap)
        action_orbits = orbits(group.elements)
        left, right = st.columns(2)
        left.metric("Enumerated elements", len(group.elements))
        right.metric("Closure status", "Truncated" if group.truncated else "Complete")
        st.plotly_chart(orbit_size_figure(action_orbits), width="stretch")
        st.plotly_chart(element_order_figure(group.elements), width="stretch")
        st.code(generator.to_cycle_notation(), language="text")
        st.caption("This is a finite permutation image, not the full infinite automorphism group.")
